name: Setup Copilot Environment
on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    name: Setup Python environment for Markdown conversion
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies for WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpango-1.0-0 \
            libharfbuzz0b \
            libpangoft2-1.0-0 \
            libpangocairo-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libffi-dev \
            shared-mime-info

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown weasyprint pygments

      - name: Verify installation
        run: |
          python --version
          python -c "import markdown; print('markdown:', markdown.__version__)"
          python -c "import weasyprint; print('weasyprint:', weasyprint.__version__)"
          python -c "import pygments; print('pygments:', pygments.__version__)"

      - name: Create output directory
        run: mkdir -p output

      - name: Test conversion script
        run: |
          # Create a test markdown file
          echo "# Test Document" > test.md
          echo "This is a test." >> test.md

          # Test conversion
          python scripts/convert_markdown.py test.md

          # Verify outputs exist
          ls -lh output/test.html output/test.pdf

          # Cleanup
          rm test.md

      - name: Environment ready
        run: |
          echo "✓ Python environment configured for Copilot"
          echo "✓ Markdown conversion dependencies installed"
          echo "✓ Conversion script tested successfully"
